language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DUCKER_HOST="$HOST_NAME"
script:
- docker build -t dtp80/htmltest .
- docker push dtp80/htmltest
after_success:
- docker run -p 8088:88 -d dto80/htmltest:latest
service: docker
env:
  global:
    secure: I9an7vXFovkljG7Sb5iy3+lRCjdKoabYdzufXX9+mmDg6Lu000LDeoXGdJemuvUgjz5YsnNHasH7jbFwAl3dd3uP3Ck5G4C5AU+5Tji9jasx+zLh/zFI9pV1GZ/xZoyZ0rJoFuo+U6a9OmhLEo5HodF4L4ucwEQcUhR/H1iWW2L36q5j5P4/2gg38n+9WGvWMwzdxehXOvNRtt4OlaW8me54HpG4aw1waH5FDESKfZ3qRyijjRulU9I/E6vvb48yVwQHYPeZcGvz06/vM+E58wbRrJg+O+y3JmN3oTx20SxGtc+QxbqlVXrr4Ib374m0y/MTA45/uJOXw6YdlF+U+HEo1K/3MC25dPrde6rMy8o42p6dPnhMSuWAfPpi5esqK1NawKTCt3NQD+7DR0oTq8KGbc8MV+r5PC/uQ7xfRVGkFfUujTt5swRBtEHA1XKaaGO5T88kxPr30Nz6gTDhAXpx38W522XtriiHjqv8Tvd1Cavd/nFl5JlS0HuDnb/XmO1Lutn1qimHc11woOpqQO2GPceEca9jYCk8TDXWZob1hajvz+wq7mvn40U6pi7XULznqW/lsSLMMkJ8u4vu0LzGM+8Q5yYg1a4+Ncq76B+cDhdM8hyBfyRSVjrhCPzskVR09dLajaPS0hytEgEqwPkQeBrYnc8/S9QqGuFL5oE=
dd:
  secure: Fw2LAFOPzp3+2Wvbp6lG3W7PbxhBPapkRdPmAiVKC+b2uxvQnvFvPWjAvN/1RRmKfXOqKFjtGY8EdwjWBSfd43Qwf+vyI2W/eAcsfokGA2ilYW7tbL+cjJLitAjr+l9Poc3AxyvSELzfS401BoEqtVT6LLozOljz++UsFWWhG33BuuPJSoj658WuWnsu/IEKYgqlRs+H2ktcTzyOnpqSmvWFH3REEUZ2/bXZs8OwDXftBJIX4N2UFhykiYta5PMWmg653N6YPtYNIyC2Fy5x0RHd3ZYV5bmXyISnwD12BMUqa7hl6No5LPOxci8I4WAxVpG4/EGagCfkxSPO0yvRGa8HaUHR/FXS4XIZDSDbQuMVk6TFYBvUuiJxmIeXsVftH8DE1ejuvjWz9STWmG/EgfcZKKFLdBmLNzp2Fcw2WTw7KE/NFaKwysKctmodu1B/Jhw/Ee+FtRhbko3Qgi37ArkFtZlbvU5851D/KVRE6oxn6senJRqrqa/dC2RMPBtd2ydN7CSVcG/uvqkIU1brnYVx7SyvOO5lfyjVx2LuppWWrQshwmmHMNP+VbpX5PHiZPM1X5Vw9b/eIL4d/gf/DwJSbhXBN/YblEErxfHj4KB8VTh2TssjJicDf0Jqu5loikVAuMeClHaKe4KZgrkheBIySch1uTn77c+m40ZDGi4=
