language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t $DOCKER_USERNAME/se234hardlab .
- docker push $DOCKER_USERNAME/se234hardlab
after_success:
- docker stop se234hardlab
- docker rm se234hardlab
- docker run -p 8088:80 -d --name se234hardlab $DOCKER_USERNAME/se234hardlab:latest
service: docker