language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DUCKER_HOST="$HOST_NAME"
script:
- docker build -t dtp80/htmltest .
- docker push dtp80/htmltest
after_success:
- docker run -p 8088:88 -d dto80/htmltest:latest
service: docker
env:
  global:
    secure: qouPJrisxSRKipIQ0HBmEGY8/mTtnWh9R/FAsoOi5iHjW/P3ju+qxoxdy0O34Uh/MKuWszqSBP1xSzIYy1k2Bp95ia4OVS0xT/pmieh+hMyugXpR/kSQEyTnNSHsFzcw6wTdk+88atGqnZBFpyzzPJBPlmEW2CS0Jqhc16mz6uGU4QlbzZxoHSQcpjPLVjjNc442tTEKtCN7eeHsv7KrOkKbSQ8U0dgDnYZfBxOj8WacCAwOnN7uXtSQRpV7SNsOwSPimWIR7n4SbSVdY9WM/sUuIpwn528zoQW/OcyH5UVdw08dxsD/UCZtVihTjoNIfyvmxEX1Qw2W2tPQ3qeq06s/6+Etlwz10hBJKIOD6lIAhnLRX5hNbstTg+Y4EbZorDHa+26hDU5Za4yL+kRaFcIgXvJFyqTw704QDZsYDduph8tn0yx33Z7D3HBMHo3oqfeJS2jogx8gJGDFpsU9Y814k95LcfW8zBNdjM73a5HIstym3G7cpK0kHVk/xGYEgc9Ftt3WveoTiJJA+gZLMvg3xTgXb/CSdeQDmBJL8L23s9DMiCXjZimX/0fOknhne91Zx7IF+BMwAbBf048MwEnRWvD/TnwMS5UTE6gAdvoIiMwUgtBzqeD0oQpESC+UIWy/CuR8m/bhbVmUeJKvdVVCIwhiT7SGG/mch/GDki0=
dd:
  secure: p07mDX4dua8sjsaFGu/31iH0MErnbifo8Fbx/G4SDVpVgce7z5oLLJTkAGNB/b8QD+TPTNklnJ+yqjXBiZkJfb2CYyz7jOkzBm+ErTvgvv5G6LjlPh6VgA7kT/lKPR6jZAC81+AR2xdCMXfC9Z4Q65Sw+akHXkftHmePX06BT2hieuTpZjT8zSqG6dPJS58FbJsTs392p72EYRnOU92Rd9N0EQ1mlygupSAMCvJN7CPqGc9BiczUPnj/5L3K9WnTcoahxE6yrHmxK4l5QMpSr8TI/E0jVBHz6xSqdY+Autl3aKzH75g2KiNS0oGp4oSeiHH9tHqpY8UCZr7bWNMkezx2YXGUVa/Gj0aH8oX8ylG3jEhBE2AHSONnW/wPSeEvwBrcjm4qoOHLwL5Mj78EShRNxHLEGXep6/Qqu+vIRbjA3DmV7b2q7Bnth8i+mw4mLyXJYnPXXvc+9fgysGPbeq4GQFlNOF7fxdvcJCGWXk5rYHHzAnw8ZsqUUm7S+yOSykqJzPGySkNVibwaRp8R4y8sKTHiglZf111QayA2fxe4lXNcWtFuucDYRgBoEYOB+qLVlkh3IHnSSo0SiPHFdJXKXo7+cQZ0NLrSeIYzp71WhpeL1vR39ogrcOkZNMBSU7Wz8hJvhoPklEsihLJUfcAmJ88fy5pMnweLHeHry7Q=
